name: Build and Deploy

on:
  push:
    branches:
      - main

env:
  AWS_ROLE_ARN: "arn:aws:iam::410185156938:role/test-IAMRole-CIHT2C99QWXZ" # GitHub Actions OIDC用IAMロール
  ECR_REPOSITORY_NAME: "test-ecr-a34kr04szwpv"  # ECRリポジトリ名

jobs:
  Build:
    runs-on: ubuntu-20.04
    permissions:
      id-token: write
      contents: read
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: ap-northeast-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 11

      - name: Build with SBT
        run: sbt Docker/publishLocal

      - name: set image tag
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ env.ECR_REPOSITORY_NAME }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker tag playground-ecs-blue-green-deploy:0.1.0-SNAPSHOT ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:${{ env.IMAGE_TAG }}
          docker push ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:${{ env.IMAGE_TAG }}